using Pine.Core.CodeAnalysis;
using Pine.Core.Elm.ElmSyntax;
using Pine.Core.Elm.ElmSyntax.SyntaxModel;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

using ModuleName = System.Collections.Generic.IReadOnlyList<string>;

using Stil4mElmSyntax7 = Pine.Core.Elm.ElmSyntax.Stil4mElmSyntax7;
using Abstract = Pine.Core.Elm.ElmSyntax.ElmSyntaxAbstract;

namespace Pine.Core.Elm.ElmCompilerInDotnet;

/// <summary>
/// Collapses structurally-equivalent declarations to a single representative,
/// rewriting all references in surviving declarations accordingly.
///
/// <para>
/// Two function declarations are considered equivalent when their
/// parameter-pattern sequences and bodies are equal after ignoring
/// every source <see cref="Range"/> / <see cref="Location"/>, declaration
/// name, type signature, and documentation. Declaration names are never
/// used to identify dedup candidates — so a declaration generated by a
/// later transformation pass (e.g. a <c>__lifted__lambdaN</c> or
/// <c>__stripped</c> sibling) can collapse against an original
/// source-level declaration that happens to share its body and patterns.
/// </para>
///
/// <para>
/// Equivalence is detected by computing a structural fingerprint per
/// declaration using <see cref="SnapshotTestFormat.RenderQualifiedDeclaration"/>
/// after stripping the signature, documentation, and substituting a
/// fixed name. The renderer already normalises away source positions
/// because formatting is derived purely from the AST shape, so two
/// declarations with identical bodies but differing token ranges
/// produce identical fingerprints.
/// </para>
///
/// <para>
/// The terminal pass runs once at the end of the optimization
/// pipeline. Reference rewriting is iterated to a fixpoint so that
/// secondary equivalences exposed by the first round of renaming are
/// collapsed too.
/// </para>
///
/// <para>
/// Implementation plan and rationale:
/// <c>explore/internal-analysis/2026-05-17-equivalent-declaration-deduplication.md</c>.
/// </para>
/// </summary>
public static class DeclarationDeduplication
{
    /// <summary>
    /// Computes the structural fingerprint of a function declaration.
    /// The fingerprint ignores declaration name, signature,
    /// documentation, and every source range/location.
    /// </summary>
    /// <remarks>
    /// We delegate to <see cref="SnapshotTestFormat.RenderQualifiedDeclaration"/>
    /// because (a) the formatter is purely structural — output depends
    /// only on the AST shape, not on token positions — and (b) reusing
    /// it avoids re-implementing a complete syntax-tree visitor for the
    /// 30+ pattern and expression variants. The signature is stripped
    /// before rendering so that two decls with the same body but
    /// different (or absent) signatures still match.
    /// </remarks>
    public static string GetStructuralFingerprint(
        Stil4mElmSyntax7.Declaration.FunctionDeclaration funcDecl,
        ModuleName currentModuleName)
    {
        var stripped = StripSignatureAndDocumentation(funcDecl);

        // Pre-qualify every intra-module reference so the renderer's
        // fully-qualified-reference validator accepts the
        // single-declaration mini-dictionary we construct below. The
        // pre-qualification also normalises away the "is the reference
        // qualified or not" distinction so that two source decls that
        // happen to differ only in unqualified-vs-qualified form for
        // the same intra-module target still fingerprint identically.
        var qualified = QualifyIntraModuleReferences(stripped, currentModuleName);

        // Use a fixed dummy qualified name; RenderQualifiedDeclaration
        // renames the decl internally so the name string never affects
        // the fingerprint.
        var dummyName = DeclQualifiedName.Create(["__dedup__"], "__decl__");

        var single =
            ImmutableDictionary.CreateRange(
                [
                new KeyValuePair<DeclQualifiedName, Stil4mElmSyntax7.Declaration>(dummyName, qualified)
                ]);

        return
            SnapshotTestFormat.RenderQualifiedDeclarations(
                single,
                SnapshotTestFormat.DeclarationSortOrder.NameAsc);
    }

    /// <summary>
    /// Abstract-model overload of
    /// <see cref="GetStructuralFingerprint(Stil4mElmSyntax7.Declaration.FunctionDeclaration, ModuleName)"/>.
    /// Bridges the abstract function declaration to the concrete
    /// model expected by the fingerprint renderer. The conversion is
    /// deterministic, so fingerprints remain stable across invocations.
    /// </summary>
    public static string GetStructuralFingerprint(
        Abstract.Declaration.FunctionDeclaration funcDecl,
        ModuleName currentModuleName) =>
        GetStructuralFingerprint(
            (Stil4mElmSyntax7.Declaration.FunctionDeclaration)
            ElmSyntaxAbstractConversion.ToDeclaration(funcDecl),
            currentModuleName);

    /// <summary>
    /// Walks the declaration's body and rewrites every
    /// <see cref="Stil4mElmSyntax7.Expression.FunctionOrValue"/> with empty
    /// <see cref="Stil4mElmSyntax7.Expression.FunctionOrValue.ModuleName"/>
    /// to use <paramref name="currentModuleName"/>. Local bindings
    /// (let-bound names, lambda parameters, case-pattern variables)
    /// are also empty-module FunctionOrValues at the AST level, so we
    /// must distinguish them from top-level references — otherwise we
    /// would mis-qualify locals and the renderer's
    /// shadow-detection would reject the result.
    /// </summary>
    private static Stil4mElmSyntax7.Declaration.FunctionDeclaration QualifyIntraModuleReferences(
        Stil4mElmSyntax7.Declaration.FunctionDeclaration funcDecl,
        ModuleName currentModuleName)
    {
        var impl = funcDecl.Function.Declaration.Value;

        // Seed local bindings with the function's own parameter names.
        var initialLocals =
            ImmutableHashSet.CreateRange(
                StringComparer.Ordinal,
                impl.Arguments.SelectMany(CollectVarPatternNames));

        var newBody =
            QualifyExpression(impl.Expression, currentModuleName, initialLocals);

        if (ReferenceEquals(newBody.Value, impl.Expression.Value))
            return funcDecl;

        return
            new Stil4mElmSyntax7.Declaration.FunctionDeclaration(
                funcDecl.Function with
                {
                    Declaration =
                    new Node<Stil4mElmSyntax7.FunctionImplementation>(
                        funcDecl.Function.Declaration.Range,
                        impl with { Expression = newBody })
                });
    }

    private static Node<Stil4mElmSyntax7.Expression> QualifyExpression(
        Node<Stil4mElmSyntax7.Expression> exprNode,
        ModuleName currentModuleName,
        ImmutableHashSet<string> locals)
    {
        var expr = exprNode.Value;

        switch (expr)
        {
            case Stil4mElmSyntax7.Expression.FunctionOrValue fov
            when fov.ModuleName.Count is 0 && !locals.Contains(fov.Name):

                {
                    return
                        new Node<Stil4mElmSyntax7.Expression>(
                            exprNode.Range,
                            new Stil4mElmSyntax7.Expression.FunctionOrValue(
                                currentModuleName,
                                fov.Name));
                }

            case Stil4mElmSyntax7.Expression.LetExpression letExpr:
                {
                    // Let-bound names enter scope across all let
                    // declarations and the body — collect them first.
                    var newLocals = locals;

                    foreach (var letDecl in letExpr.Value.Declarations)
                    {
                        switch (letDecl.Value)
                        {
                            case Stil4mElmSyntax7.Expression.LetDeclaration.LetFunction lf:
                                newLocals = newLocals.Add(lf.Function.Declaration.Value.Name.Value);
                                break;

                            case Stil4mElmSyntax7.Expression.LetDeclaration.LetDestructuring ld:
                                foreach (var n in CollectVarPatternNames(ld.Pattern))
                                    newLocals = newLocals.Add(n);

                                break;
                        }
                    }

                    var rewrittenLetDecls =
                        new List<Node<Stil4mElmSyntax7.Expression.LetDeclaration>>();

                    foreach (var letDecl in letExpr.Value.Declarations)
                    {
                        switch (letDecl.Value)
                        {
                            case Stil4mElmSyntax7.Expression.LetDeclaration.LetFunction lf:
                                {
                                    var lfImpl = lf.Function.Declaration.Value;

                                    var lfLocals =
                                        newLocals.Union(
                                            lfImpl.Arguments.SelectMany(CollectVarPatternNames));

                                    var newLfBody =
                                        QualifyExpression(
                                            lfImpl.Expression,
                                            currentModuleName,
                                            lfLocals);

                                    var newLf =
                                        new Stil4mElmSyntax7.Expression.LetDeclaration.LetFunction(
                                            lf.Function with
                                            {
                                                Declaration =
                                                new Node<Stil4mElmSyntax7.FunctionImplementation>(
                                                    lf.Function.Declaration.Range,
                                                    lfImpl with { Expression = newLfBody })
                                            });

                                    rewrittenLetDecls.Add(
                                        new Node<Stil4mElmSyntax7.Expression.LetDeclaration>(letDecl.Range, newLf));

                                    break;
                                }

                            case Stil4mElmSyntax7.Expression.LetDeclaration.LetDestructuring ld:
                                {
                                    var newLdExpr =
                                        QualifyExpression(ld.Expression, currentModuleName, locals);

                                    rewrittenLetDecls.Add(
                                        new Node<Stil4mElmSyntax7.Expression.LetDeclaration>(
                                            letDecl.Range,
                                            new Stil4mElmSyntax7.Expression.LetDeclaration.LetDestructuring(
                                                ld.Pattern,
                                                newLdExpr)));

                                    break;
                                }

                            default:
                                rewrittenLetDecls.Add(letDecl);
                                break;
                        }
                    }

                    var rewrittenLetBody =
                        QualifyExpression(letExpr.Value.Expression, currentModuleName, newLocals);

                    return
                        new Node<Stil4mElmSyntax7.Expression>(
                            exprNode.Range,
                            new Stil4mElmSyntax7.Expression.LetExpression(
                                new Stil4mElmSyntax7.Expression.LetBlock(
                                    rewrittenLetDecls,
                                    rewrittenLetBody)));
                }

            case Stil4mElmSyntax7.Expression.LambdaExpression lambda:
                {
                    var lambdaLocals =
                        locals.Union(
                            lambda.Lambda.Arguments.SelectMany(CollectVarPatternNames));

                    var newLambdaBody =
                        QualifyExpression(lambda.Lambda.Expression, currentModuleName, lambdaLocals);

                    return
                        new Node<Stil4mElmSyntax7.Expression>(
                            exprNode.Range,
                            new Stil4mElmSyntax7.Expression.LambdaExpression(
                                new Stil4mElmSyntax7.LambdaStruct(
                                    lambda.Lambda.Arguments,
                                    newLambdaBody)));
                }

            case Stil4mElmSyntax7.Expression.CaseExpression caseExpr:
                {
                    var newScrutinee =
                        QualifyExpression(caseExpr.CaseBlock.Expression, currentModuleName, locals);

                    var newCases =
                        caseExpr.CaseBlock.Cases.Select(
                            c =>
                            {
                                var branchLocals = locals.Union(CollectVarPatternNames(c.Pattern));

                                return
                                    new Stil4mElmSyntax7.Case(
                                        c.Pattern,
                                        QualifyExpression(c.Expression, currentModuleName, branchLocals));
                            }).ToList();

                    return
                        new Node<Stil4mElmSyntax7.Expression>(
                            exprNode.Range,
                            new Stil4mElmSyntax7.Expression.CaseExpression(
                                new Stil4mElmSyntax7.CaseBlock(newScrutinee, newCases)));
                }

            default:
                {
                    var anyChanged = false;

                    Node<Stil4mElmSyntax7.Expression> Recurse(Node<Stil4mElmSyntax7.Expression> child)
                    {
                        var newChild = QualifyExpression(child, currentModuleName, locals);

                        if (!ReferenceEquals(newChild.Value, child.Value))
                            anyChanged = true;

                        return newChild;
                    }

                    var rewritten = ElmSyntaxTransformations.MapChildExpressions(expr, Recurse);

                    if (!anyChanged)
                        return exprNode;

                    return new Node<Stil4mElmSyntax7.Expression>(exprNode.Range, rewritten);
                }
        }
    }

    /// <summary>
    /// Returns every name introduced by a pattern (recursively).
    /// Used by <see cref="QualifyIntraModuleReferences"/> to seed local
    /// bindings so they are not mis-qualified as top-level references.
    /// </summary>
    private static IEnumerable<string> CollectVarPatternNames(Node<Stil4mElmSyntax7.Pattern> patternNode)
    {
        return CollectVarPatternNames(patternNode.Value);
    }

    private static IEnumerable<string> CollectVarPatternNames(Stil4mElmSyntax7.Pattern pattern)
    {
        switch (pattern)
        {
            case Stil4mElmSyntax7.Pattern.VarPattern vp:
                yield return vp.Name;
                break;

            case Stil4mElmSyntax7.Pattern.TuplePattern tp:
                foreach (var el in tp.Elements)
                    foreach (var n in CollectVarPatternNames(el))
                        yield return n;

                break;

            case Stil4mElmSyntax7.Pattern.RecordPattern rp:
                foreach (var f in rp.Fields)
                    yield return f.Value;

                break;

            case Stil4mElmSyntax7.Pattern.UnConsPattern uc:
                foreach (var n in CollectVarPatternNames(uc.Head))
                    yield return n;

                foreach (var n in CollectVarPatternNames(uc.Tail))
                    yield return n;

                break;

            case Stil4mElmSyntax7.Pattern.ListPattern lp:
                foreach (var el in lp.Elements)
                    foreach (var n in CollectVarPatternNames(el))
                        yield return n;

                break;

            case Stil4mElmSyntax7.Pattern.NamedPattern np:
                foreach (var arg in np.Arguments)
                    foreach (var n in CollectVarPatternNames(arg))
                        yield return n;

                break;

            case Stil4mElmSyntax7.Pattern.AsPattern ap:
                foreach (var n in CollectVarPatternNames(ap.Pattern))
                    yield return n;

                yield return ap.Name.Value;
                break;

            case Stil4mElmSyntax7.Pattern.ParenthesizedPattern pp:
                foreach (var n in CollectVarPatternNames(pp.Pattern))
                    yield return n;

                break;
        }
    }

    private static Stil4mElmSyntax7.Declaration.FunctionDeclaration StripSignatureAndDocumentation(
        Stil4mElmSyntax7.Declaration.FunctionDeclaration funcDecl) =>
        new(
            funcDecl.Function with
            {
                Documentation = null,
                Signature = null,
            });

    /// <summary>
    /// Bottom-up rewrite of every <see cref="Stil4mElmSyntax7.Expression.FunctionOrValue"/>
    /// in the tree. Returns the original node unchanged when no
    /// rename fires anywhere, so callers can short-circuit via
    /// reference equality.
    /// </summary>
    private static Node<Stil4mElmSyntax7.Expression> RewriteReferencesInExpression(
        Node<Stil4mElmSyntax7.Expression> exprNode,
        IReadOnlyDictionary<DeclQualifiedName, DeclQualifiedName> renameMap,
        ModuleName currentModuleName)
    {
        var expr = exprNode.Value;

        // Rewrite the FunctionOrValue leaf in place.
        if (expr is Stil4mElmSyntax7.Expression.FunctionOrValue fov)
        {
            var rewrittenFov =
                TryRewriteFunctionOrValue(fov, renameMap, currentModuleName);

            if (rewrittenFov is null)
                return exprNode;

            return new Node<Stil4mElmSyntax7.Expression>(exprNode.Range, rewrittenFov);
        }

        // For every composite expression, recurse into children. Track
        // whether any child changed so we only allocate a fresh node
        // when needed.
        var anyChildChanged = false;

        Node<Stil4mElmSyntax7.Expression> Recurse(Node<Stil4mElmSyntax7.Expression> child)
        {
            var newChild = RewriteReferencesInExpression(child, renameMap, currentModuleName);

            if (!ReferenceEquals(newChild.Value, child.Value))
                anyChildChanged = true;

            return newChild;
        }

        var rewrittenExpr = ElmSyntaxTransformations.MapChildExpressions(expr, Recurse);

        if (!anyChildChanged)
            return exprNode;

        return new Node<Stil4mElmSyntax7.Expression>(exprNode.Range, rewrittenExpr);
    }

    /// <summary>
    /// Attempts to rewrite a single <see cref="Stil4mElmSyntax7.Expression.FunctionOrValue"/>
    /// using the provided rename map. Returns null when the reference
    /// does not resolve to any dedup'd declaration.
    /// </summary>
    private static Stil4mElmSyntax7.Expression.FunctionOrValue? TryRewriteFunctionOrValue(
        Stil4mElmSyntax7.Expression.FunctionOrValue fov,
        IReadOnlyDictionary<DeclQualifiedName, DeclQualifiedName> renameMap,
        ModuleName currentModuleName)
    {
        // Resolve the reference to a DeclQualifiedName candidate. An
        // empty ModuleName means the reference is intra-module; resolve
        // against currentModuleName.
        var candidate =
            fov.ModuleName.Count is 0
            ?
            DeclQualifiedName.Create(currentModuleName, fov.Name)
            :
            DeclQualifiedName.Create(fov.ModuleName, fov.Name);

        if (!renameMap.TryGetValue(candidate, out var target))
            return null;

        // Rebuild as a fully-qualified reference targeting the chosen
        // representative. We always emit the qualified module name even
        // for intra-module reuses — downstream passes (notably Application
        // normalization and the dependency-layout build) are happiest
        // when the module path is explicit and there is no ambiguity
        // about the resolution.
        return
            new Stil4mElmSyntax7.Expression.FunctionOrValue(
                ModuleName: target.Namespaces,
                Name: target.DeclName);
    }
}
