using Pine.Core.CodeAnalysis;
using Pine.Core.Elm.ElmSyntax;
using Pine.Core.Elm.ElmSyntax.SyntaxModel;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

using ModuleName = System.Collections.Generic.IReadOnlyList<string>;

using SyntaxTypes = Pine.Core.Elm.ElmSyntax.Stil4mElmSyntax7;

namespace Pine.Core.Elm.ElmCompilerInDotnet;

/// <summary>
/// Collapses structurally-equivalent declarations to a single representative,
/// rewriting all references in surviving declarations accordingly.
///
/// <para>
/// Two function declarations are considered equivalent when their
/// parameter-pattern sequences and bodies are equal after ignoring
/// every source <see cref="Range"/> / <see cref="Location"/>, declaration
/// name, type signature, and documentation. Declaration names are never
/// used to identify dedup candidates — so a declaration generated by a
/// later transformation pass (e.g. a <c>__lifted__lambdaN</c> or
/// <c>__stripped</c> sibling) can collapse against an original
/// source-level declaration that happens to share its body and patterns.
/// </para>
///
/// <para>
/// Equivalence is detected by computing a structural fingerprint per
/// declaration using <see cref="SnapshotTestFormat.RenderQualifiedDeclaration"/>
/// after stripping the signature, documentation, and substituting a
/// fixed name. The renderer already normalises away source positions
/// because formatting is derived purely from the AST shape, so two
/// declarations with identical bodies but differing token ranges
/// produce identical fingerprints.
/// </para>
///
/// <para>
/// The terminal pass runs once at the end of the optimization
/// pipeline. Reference rewriting is iterated to a fixpoint so that
/// secondary equivalences exposed by the first round of renaming are
/// collapsed too.
/// </para>
///
/// <para>
/// Implementation plan and rationale:
/// <c>explore/internal-analysis/2026-05-17-equivalent-declaration-deduplication.md</c>.
/// </para>
/// </summary>
public static class DeclarationDeduplication
{
    /// <summary>
    /// Synthetic name suffixes whose presence indicates that a
    /// declaration was generated by a transformation pass rather than
    /// written by the source author. Used only as a tie-breaker when
    /// picking the representative within an equivalence class — never
    /// to gate equivalence detection itself.
    /// </summary>
    private static readonly string[] s_syntheticSuffixes =
        [
        GeneratedNameSuffixes.Lifted,
        GeneratedNameSuffixes.Stripped,
        GeneratedNameSuffixes.Specialized,
        "__lambda",
        ];

    /// <summary>
    /// Hard upper bound on the number of dedup iterations. Each
    /// iteration must strictly reduce the declaration count, so this
    /// is mostly a guard against unforeseen pathological cycles.
    /// </summary>
    private const int MaxIterations = 16;

    /// <summary>
    /// Runs the equivalence-based dedup to a fixpoint and returns the
    /// resulting declaration dictionary. Returns the input dictionary
    /// unchanged when no equivalences are found.
    ///
    /// <para>
    /// Declarations whose qualified names appear in <paramref name="preserveDeclNames"/>
    /// are never removed from the dictionary — their bodies are
    /// replaced by a forwarding call to the chosen representative
    /// instead. This is necessary because downstream stages
    /// (notably <see cref="ElmCompiler.ReconstructModulesFromFlatDict"/>)
    /// fall back to the pre-optimization body when a declaration
    /// originally present in the source module is missing from the
    /// optimization output. The forwarding stub preserves the call
    /// surface so subsequent passes still see the same set of
    /// top-level callables.
    /// </para>
    /// </summary>
    public static ImmutableDictionary<DeclQualifiedName, SyntaxTypes.Declaration>
        RewriteDeclarationDictionary(
        ImmutableDictionary<DeclQualifiedName, SyntaxTypes.Declaration> declarations,
        IReadOnlySet<DeclQualifiedName> preserveDeclNames)
    {
        var current = declarations;

        for (var iteration = 0; iteration < MaxIterations; iteration++)
        {
            var next = DedupOnePass(current, preserveDeclNames);

            if (next.Count == current.Count &&
                ReferenceEquals(next, current))
                return next;

            // Reference equality short-circuits when nothing changed.
            if (ReferenceEquals(next, current))
                return next;

            current = next;
        }

        return current;
    }

    /// <summary>
    /// Convenience overload: dedup without preserving any declaration
    /// names. Intended for tests and stand-alone use; the production
    /// pipeline always supplies an explicit preserve set.
    /// </summary>
    public static ImmutableDictionary<DeclQualifiedName, SyntaxTypes.Declaration>
        RewriteDeclarationDictionary(
        ImmutableDictionary<DeclQualifiedName, SyntaxTypes.Declaration> declarations) =>
        RewriteDeclarationDictionary(declarations, preserveDeclNames: new HashSet<DeclQualifiedName>());

    /// <summary>
    /// One pass of: group function decls by fingerprint, pick a
    /// representative per group, rewrite every reference, drop or
    /// replace-with-forwarder the redundant decls depending on
    /// whether they appear in <paramref name="preserveDeclNames"/>.
    /// </summary>
    private static ImmutableDictionary<DeclQualifiedName, SyntaxTypes.Declaration>
        DedupOnePass(
        ImmutableDictionary<DeclQualifiedName, SyntaxTypes.Declaration> declarations,
        IReadOnlySet<DeclQualifiedName> preserveDeclNames)
    {
        // 1. Compute fingerprints for every function decl.
        var byFingerprint = new Dictionary<string, List<DeclQualifiedName>>(StringComparer.Ordinal);

        foreach (var (name, decl) in declarations)
        {
            if (decl is not SyntaxTypes.Declaration.FunctionDeclaration funcDecl)
                continue;

            // Exclude declarations with no parameters and a body that is a single literal,
            // since these are typically intentionally distinct top-level constants whose
            // name is meaningful at call sites (e.g. message strings).
            // Equivalence dedup of such constants would be name-driven anyway from a
            // human readability standpoint — leave them alone.
            // NOTE: only the no-parameter-and-literal-only case is excluded; any decl
            // with at least one parameter or a non-literal body remains a dedup candidate.
            if (IsPlainLiteralValueDecl(funcDecl))
                continue;

            var fp = GetStructuralFingerprint(funcDecl, name.Namespaces);

            if (!byFingerprint.TryGetValue(fp, out var list))
            {
                list = [];
                byFingerprint[fp] = list;
            }

            list.Add(name);
        }

        // 2. Build the rename map for every multi-member group. Two
        //    preserved (original-source) declarations are never
        //    collapsed together — the user wrote them separately and
        //    each may carry distinct downstream lowering through
        //    subsequent passes (e.g. operator lowering specialises
        //    Basics.* calls into Pine_builtin.* in-place, and turning
        //    an inlined body into a forwarder would undo that). The
        //    purpose of dedup is to fold the *synthetic* duplicates
        //    emitted by intermediate passes (`__lifted__lambdaN`,
        //    `__stripped`, `__specialized__N`) onto a single
        //    representative — preferably an original source decl.
        //
        //    Concretely, for each fingerprint group:
        //    - If the group contains zero preserved decls, collapse
        //      every member to the first one (pure synthetic dedup).
        //    - If the group contains exactly one preserved decl, that
        //      preserved decl is the representative and the synthetic
        //      members are removed entirely (their refs rewrite).
        //    - If the group contains two or more preserved decls,
        //      DO NOT collapse the preserved members — they remain
        //      distinct. Any synthetic member is folded onto the
        //      first preserved decl.
        var renameMap = new Dictionary<DeclQualifiedName, DeclQualifiedName>();
        var toRemove = new HashSet<DeclQualifiedName>();

        foreach (var group in byFingerprint.Values)
        {
            if (group.Count <= 1)
                continue;

            var preservedInGroup =
                group.Where(preserveDeclNames.Contains).ToList();

            DeclQualifiedName representative;

            if (preservedInGroup.Count >= 1)
            {
                // Representative is the first preserved decl in
                // canonical ordering — synthetic suffix count then
                // lexicographic.
                representative = PickRepresentative(preservedInGroup, preserveDeclNames);
            }
            else
            {
                representative = PickRepresentative(group, preserveDeclNames);
            }

            foreach (var name in group)
            {
                if (name.Equals(representative))
                    continue;

                if (preserveDeclNames.Contains(name))
                {
                    // Multiple preserved decls in the same equivalence
                    // class: leave the non-representative preserved
                    // decl alone. We do NOT rewrite references to it
                    // either — its identity is meaningful to the
                    // source author and downstream passes.
                    continue;
                }

                renameMap[name] = representative;
                toRemove.Add(name);
            }
        }

        if (renameMap.Count is 0)
            return declarations;

        // 3. Rewrite every reference in the surviving decls.
        var builder = ImmutableDictionary.CreateBuilder<DeclQualifiedName, SyntaxTypes.Declaration>();

        foreach (var (name, decl) in declarations)
        {
            if (toRemove.Contains(name))
                continue;

            builder[name] = RewriteReferencesInDeclaration(decl, renameMap, name.Namespaces);
        }

        return builder.ToImmutable();
    }

    /// <summary>
    /// True iff <paramref name="funcDecl"/> takes zero parameters and
    /// has a single literal-leaf body (Integer / Hex / Float / Literal /
    /// CharLiteral / UnitExpr). Such declarations are usually
    /// intentional named constants and excluding them from dedup
    /// avoids surprising the reader by silently renaming references.
    /// </summary>
    private static bool IsPlainLiteralValueDecl(
        SyntaxTypes.Declaration.FunctionDeclaration funcDecl)
    {
        var impl = funcDecl.Function.Declaration.Value;

        if (impl.Arguments.Count is not 0)
            return false;

        return
            impl.Expression.Value is
            SyntaxTypes.Expression.Integer or
            SyntaxTypes.Expression.Hex or
            SyntaxTypes.Expression.Floatable or
            SyntaxTypes.Expression.Literal or
            SyntaxTypes.Expression.CharLiteral or
            SyntaxTypes.Expression.UnitExpr;
    }

    /// <summary>
    /// Selects the preferred name within an equivalence class.
    /// Selection priority is purely a UX preference — equivalence
    /// detection itself never inspects names (per the design rule).
    /// <list type="number">
    /// <item>Fewest synthetic-suffix occurrences (so an original source
    /// decl wins over a generated <c>__stripped</c> / <c>__lifted__</c> /
    /// <c>__specialized__</c> sibling).</item>
    /// <item>Lexicographically smallest by full qualified name (so
    /// <c>__lambda1</c> wins over <c>__lambda3</c> among siblings of
    /// the same kind).</item>
    /// </list>
    /// </summary>
    private static DeclQualifiedName PickRepresentative(
        IReadOnlyList<DeclQualifiedName> names,
        IReadOnlySet<DeclQualifiedName> preserveDeclNames)
    {
        return
            names
            .OrderBy(n => preserveDeclNames.Contains(n) ? 0 : 1)
            .ThenBy(n => CountSyntheticSuffixOccurrences(n.DeclName))
            .ThenBy(n => n)
            .First();
    }

    private static int CountSyntheticSuffixOccurrences(string name)
    {
        var total = 0;

        foreach (var suffix in s_syntheticSuffixes)
        {
            var idx = 0;

            while ((idx = name.IndexOf(suffix, idx, StringComparison.Ordinal)) >= 0)
            {
                total++;
                idx += suffix.Length;
            }
        }

        return total;
    }

    /// <summary>
    /// Computes the structural fingerprint of a function declaration.
    /// The fingerprint ignores declaration name, signature,
    /// documentation, and every source range/location.
    /// </summary>
    /// <remarks>
    /// We delegate to <see cref="SnapshotTestFormat.RenderQualifiedDeclaration"/>
    /// because (a) the formatter is purely structural — output depends
    /// only on the AST shape, not on token positions — and (b) reusing
    /// it avoids re-implementing a complete syntax-tree visitor for the
    /// 30+ pattern and expression variants. The signature is stripped
    /// before rendering so that two decls with the same body but
    /// different (or absent) signatures still match.
    /// </remarks>
    public static string GetStructuralFingerprint(
        SyntaxTypes.Declaration.FunctionDeclaration funcDecl,
        ModuleName currentModuleName)
    {
        var stripped = StripSignatureAndDocumentation(funcDecl);

        // Pre-qualify every intra-module reference so the renderer's
        // fully-qualified-reference validator accepts the
        // single-declaration mini-dictionary we construct below. The
        // pre-qualification also normalises away the "is the reference
        // qualified or not" distinction so that two source decls that
        // happen to differ only in unqualified-vs-qualified form for
        // the same intra-module target still fingerprint identically.
        var qualified = QualifyIntraModuleReferences(stripped, currentModuleName);

        // Use a fixed dummy qualified name; RenderQualifiedDeclaration
        // renames the decl internally so the name string never affects
        // the fingerprint.
        var dummyName = new DeclQualifiedName(["__dedup__"], "__decl__");

        var single =
            ImmutableDictionary.CreateRange(
                [
                new KeyValuePair<DeclQualifiedName, SyntaxTypes.Declaration>(dummyName, qualified)
                ]);

        return
            SnapshotTestFormat.RenderQualifiedDeclarations(
                single,
                SnapshotTestFormat.DeclarationSortOrder.NameAsc);
    }

    /// <summary>
    /// Walks the declaration's body and rewrites every
    /// <see cref="SyntaxTypes.Expression.FunctionOrValue"/> with empty
    /// <see cref="SyntaxTypes.Expression.FunctionOrValue.ModuleName"/>
    /// to use <paramref name="currentModuleName"/>. Local bindings
    /// (let-bound names, lambda parameters, case-pattern variables)
    /// are also empty-module FunctionOrValues at the AST level, so we
    /// must distinguish them from top-level references — otherwise we
    /// would mis-qualify locals and the renderer's
    /// shadow-detection would reject the result.
    /// </summary>
    private static SyntaxTypes.Declaration.FunctionDeclaration QualifyIntraModuleReferences(
        SyntaxTypes.Declaration.FunctionDeclaration funcDecl,
        ModuleName currentModuleName)
    {
        var impl = funcDecl.Function.Declaration.Value;

        // Seed local bindings with the function's own parameter names.
        var initialLocals =
            ImmutableHashSet.CreateRange(
                StringComparer.Ordinal,
                impl.Arguments.SelectMany(CollectVarPatternNames));

        var newBody =
            QualifyExpression(impl.Expression, currentModuleName, initialLocals);

        if (ReferenceEquals(newBody.Value, impl.Expression.Value))
            return funcDecl;

        return
            new SyntaxTypes.Declaration.FunctionDeclaration(
                funcDecl.Function with
                {
                    Declaration =
                    new Node<SyntaxTypes.FunctionImplementation>(
                        funcDecl.Function.Declaration.Range,
                        impl with { Expression = newBody })
                });
    }

    private static Node<SyntaxTypes.Expression> QualifyExpression(
        Node<SyntaxTypes.Expression> exprNode,
        ModuleName currentModuleName,
        ImmutableHashSet<string> locals)
    {
        var expr = exprNode.Value;

        switch (expr)
        {
            case SyntaxTypes.Expression.FunctionOrValue fov
            when fov.ModuleName.Count is 0 && !locals.Contains(fov.Name):

                {
                    return
                        new Node<SyntaxTypes.Expression>(
                            exprNode.Range,
                            new SyntaxTypes.Expression.FunctionOrValue(
                                currentModuleName,
                                fov.Name));
                }

            case SyntaxTypes.Expression.LetExpression letExpr:
                {
                    // Let-bound names enter scope across all let
                    // declarations and the body — collect them first.
                    var newLocals = locals;

                    foreach (var letDecl in letExpr.Value.Declarations)
                    {
                        switch (letDecl.Value)
                        {
                            case SyntaxTypes.Expression.LetDeclaration.LetFunction lf:
                                newLocals = newLocals.Add(lf.Function.Declaration.Value.Name.Value);
                                break;

                            case SyntaxTypes.Expression.LetDeclaration.LetDestructuring ld:
                                foreach (var n in CollectVarPatternNames(ld.Pattern))
                                    newLocals = newLocals.Add(n);

                                break;
                        }
                    }

                    var rewrittenLetDecls =
                        new List<Node<SyntaxTypes.Expression.LetDeclaration>>();

                    foreach (var letDecl in letExpr.Value.Declarations)
                    {
                        switch (letDecl.Value)
                        {
                            case SyntaxTypes.Expression.LetDeclaration.LetFunction lf:
                                {
                                    var lfImpl = lf.Function.Declaration.Value;

                                    var lfLocals =
                                        newLocals.Union(
                                            lfImpl.Arguments.SelectMany(CollectVarPatternNames));

                                    var newLfBody =
                                        QualifyExpression(
                                            lfImpl.Expression,
                                            currentModuleName,
                                            lfLocals);

                                    var newLf =
                                        new SyntaxTypes.Expression.LetDeclaration.LetFunction(
                                            lf.Function with
                                            {
                                                Declaration =
                                                new Node<SyntaxTypes.FunctionImplementation>(
                                                    lf.Function.Declaration.Range,
                                                    lfImpl with { Expression = newLfBody })
                                            });

                                    rewrittenLetDecls.Add(
                                        new Node<SyntaxTypes.Expression.LetDeclaration>(letDecl.Range, newLf));

                                    break;
                                }

                            case SyntaxTypes.Expression.LetDeclaration.LetDestructuring ld:
                                {
                                    var newLdExpr =
                                        QualifyExpression(ld.Expression, currentModuleName, locals);

                                    rewrittenLetDecls.Add(
                                        new Node<SyntaxTypes.Expression.LetDeclaration>(
                                            letDecl.Range,
                                            new SyntaxTypes.Expression.LetDeclaration.LetDestructuring(
                                                ld.Pattern,
                                                newLdExpr)));

                                    break;
                                }

                            default:
                                rewrittenLetDecls.Add(letDecl);
                                break;
                        }
                    }

                    var rewrittenLetBody =
                        QualifyExpression(letExpr.Value.Expression, currentModuleName, newLocals);

                    return
                        new Node<SyntaxTypes.Expression>(
                            exprNode.Range,
                            new SyntaxTypes.Expression.LetExpression(
                                new SyntaxTypes.Expression.LetBlock(
                                    rewrittenLetDecls,
                                    rewrittenLetBody)));
                }

            case SyntaxTypes.Expression.LambdaExpression lambda:
                {
                    var lambdaLocals =
                        locals.Union(
                            lambda.Lambda.Arguments.SelectMany(CollectVarPatternNames));

                    var newLambdaBody =
                        QualifyExpression(lambda.Lambda.Expression, currentModuleName, lambdaLocals);

                    return
                        new Node<SyntaxTypes.Expression>(
                            exprNode.Range,
                            new SyntaxTypes.Expression.LambdaExpression(
                                new SyntaxTypes.LambdaStruct(
                                    lambda.Lambda.Arguments,
                                    newLambdaBody)));
                }

            case SyntaxTypes.Expression.CaseExpression caseExpr:
                {
                    var newScrutinee =
                        QualifyExpression(caseExpr.CaseBlock.Expression, currentModuleName, locals);

                    var newCases =
                        caseExpr.CaseBlock.Cases.Select(
                            c =>
                            {
                                var branchLocals = locals.Union(CollectVarPatternNames(c.Pattern));

                                return
                                    new SyntaxTypes.Case(
                                        c.Pattern,
                                        QualifyExpression(c.Expression, currentModuleName, branchLocals));
                            }).ToList();

                    return
                        new Node<SyntaxTypes.Expression>(
                            exprNode.Range,
                            new SyntaxTypes.Expression.CaseExpression(
                                new SyntaxTypes.CaseBlock(newScrutinee, newCases)));
                }

            default:
                {
                    var anyChanged = false;

                    Node<SyntaxTypes.Expression> Recurse(Node<SyntaxTypes.Expression> child)
                    {
                        var newChild = QualifyExpression(child, currentModuleName, locals);

                        if (!ReferenceEquals(newChild.Value, child.Value))
                            anyChanged = true;

                        return newChild;
                    }

                    var rewritten = ElmSyntaxTransformations.MapChildExpressions(expr, Recurse);

                    if (!anyChanged)
                        return exprNode;

                    return new Node<SyntaxTypes.Expression>(exprNode.Range, rewritten);
                }
        }
    }

    /// <summary>
    /// Returns every name introduced by a pattern (recursively).
    /// Used by <see cref="QualifyIntraModuleReferences"/> to seed local
    /// bindings so they are not mis-qualified as top-level references.
    /// </summary>
    private static IEnumerable<string> CollectVarPatternNames(Node<SyntaxTypes.Pattern> patternNode)
    {
        return CollectVarPatternNames(patternNode.Value);
    }

    private static IEnumerable<string> CollectVarPatternNames(SyntaxTypes.Pattern pattern)
    {
        switch (pattern)
        {
            case SyntaxTypes.Pattern.VarPattern vp:
                yield return vp.Name;
                break;

            case SyntaxTypes.Pattern.TuplePattern tp:
                foreach (var el in tp.Elements)
                    foreach (var n in CollectVarPatternNames(el))
                        yield return n;

                break;

            case SyntaxTypes.Pattern.RecordPattern rp:
                foreach (var f in rp.Fields)
                    yield return f.Value;

                break;

            case SyntaxTypes.Pattern.UnConsPattern uc:
                foreach (var n in CollectVarPatternNames(uc.Head))
                    yield return n;

                foreach (var n in CollectVarPatternNames(uc.Tail))
                    yield return n;

                break;

            case SyntaxTypes.Pattern.ListPattern lp:
                foreach (var el in lp.Elements)
                    foreach (var n in CollectVarPatternNames(el))
                        yield return n;

                break;

            case SyntaxTypes.Pattern.NamedPattern np:
                foreach (var arg in np.Arguments)
                    foreach (var n in CollectVarPatternNames(arg))
                        yield return n;

                break;

            case SyntaxTypes.Pattern.AsPattern ap:
                foreach (var n in CollectVarPatternNames(ap.Pattern))
                    yield return n;

                yield return ap.Name.Value;
                break;

            case SyntaxTypes.Pattern.ParenthesizedPattern pp:
                foreach (var n in CollectVarPatternNames(pp.Pattern))
                    yield return n;

                break;
        }
    }

    private static SyntaxTypes.Declaration.FunctionDeclaration StripSignatureAndDocumentation(
        SyntaxTypes.Declaration.FunctionDeclaration funcDecl) =>
        new(
            funcDecl.Function with
            {
                Documentation = null,
                Signature = null,
            });

    /// <summary>
    /// Rewrites all <see cref="SyntaxTypes.Expression.FunctionOrValue"/>
    /// references inside a declaration's body using
    /// <paramref name="renameMap"/>. References with an empty
    /// module-name are resolved against <paramref name="currentModuleName"/>
    /// before lookup, so intra-module references are renamed correctly.
    /// </summary>
    private static SyntaxTypes.Declaration RewriteReferencesInDeclaration(
        SyntaxTypes.Declaration decl,
        IReadOnlyDictionary<DeclQualifiedName, DeclQualifiedName> renameMap,
        ModuleName currentModuleName)
    {
        switch (decl)
        {
            case SyntaxTypes.Declaration.FunctionDeclaration funcDecl:
                {
                    var impl = funcDecl.Function.Declaration.Value;

                    var newBody =
                        RewriteReferencesInExpression(impl.Expression, renameMap, currentModuleName);

                    if (ReferenceEquals(newBody.Value, impl.Expression.Value))
                        return decl;

                    var newImpl =
                        impl with
                        {
                            Expression = newBody,
                        };

                    var newFunc =
                        funcDecl.Function with
                        {
                            Declaration =
                            new Node<SyntaxTypes.FunctionImplementation>(
                                funcDecl.Function.Declaration.Range,
                                newImpl),
                        };

                    return new SyntaxTypes.Declaration.FunctionDeclaration(newFunc);
                }

            case SyntaxTypes.Declaration.CustomTypeDeclaration:
            case SyntaxTypes.Declaration.AliasDeclaration:
            case SyntaxTypes.Declaration.PortDeclaration:
            case SyntaxTypes.Declaration.InfixDeclaration:
                return decl;

            default:
                throw new NotImplementedException(
                    "DeclarationDeduplication.RewriteReferencesInDeclaration does not handle " +
                    "declaration variant: " + decl.GetType().Name);
        }
    }

    /// <summary>
    /// Bottom-up rewrite of every <see cref="SyntaxTypes.Expression.FunctionOrValue"/>
    /// in the tree. Returns the original node unchanged when no
    /// rename fires anywhere, so callers can short-circuit via
    /// reference equality.
    /// </summary>
    private static Node<SyntaxTypes.Expression> RewriteReferencesInExpression(
        Node<SyntaxTypes.Expression> exprNode,
        IReadOnlyDictionary<DeclQualifiedName, DeclQualifiedName> renameMap,
        ModuleName currentModuleName)
    {
        var expr = exprNode.Value;

        // Rewrite the FunctionOrValue leaf in place.
        if (expr is SyntaxTypes.Expression.FunctionOrValue fov)
        {
            var rewrittenFov =
                TryRewriteFunctionOrValue(fov, renameMap, currentModuleName);

            if (rewrittenFov is null)
                return exprNode;

            return new Node<SyntaxTypes.Expression>(exprNode.Range, rewrittenFov);
        }

        // For every composite expression, recurse into children. Track
        // whether any child changed so we only allocate a fresh node
        // when needed.
        var anyChildChanged = false;

        Node<SyntaxTypes.Expression> Recurse(Node<SyntaxTypes.Expression> child)
        {
            var newChild = RewriteReferencesInExpression(child, renameMap, currentModuleName);

            if (!ReferenceEquals(newChild.Value, child.Value))
                anyChildChanged = true;

            return newChild;
        }

        var rewrittenExpr = ElmSyntaxTransformations.MapChildExpressions(expr, Recurse);

        if (!anyChildChanged)
            return exprNode;

        return new Node<SyntaxTypes.Expression>(exprNode.Range, rewrittenExpr);
    }

    /// <summary>
    /// Attempts to rewrite a single <see cref="SyntaxTypes.Expression.FunctionOrValue"/>
    /// using the provided rename map. Returns null when the reference
    /// does not resolve to any dedup'd declaration.
    /// </summary>
    private static SyntaxTypes.Expression.FunctionOrValue? TryRewriteFunctionOrValue(
        SyntaxTypes.Expression.FunctionOrValue fov,
        IReadOnlyDictionary<DeclQualifiedName, DeclQualifiedName> renameMap,
        ModuleName currentModuleName)
    {
        // Resolve the reference to a DeclQualifiedName candidate. An
        // empty ModuleName means the reference is intra-module; resolve
        // against currentModuleName.
        var candidate =
            fov.ModuleName.Count is 0
            ?
            new DeclQualifiedName(currentModuleName, fov.Name)
            :
            new DeclQualifiedName(fov.ModuleName, fov.Name);

        if (!renameMap.TryGetValue(candidate, out var target))
            return null;

        // Rebuild as a fully-qualified reference targeting the chosen
        // representative. We always emit the qualified module name even
        // for intra-module reuses — downstream passes (notably Application
        // normalization and the dependency-layout build) are happiest
        // when the module path is explicit and there is no ambiguity
        // about the resolution.
        return
            new SyntaxTypes.Expression.FunctionOrValue(
                ModuleName: target.Namespaces,
                Name: target.DeclName);
    }
}
